### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by systra72** [predictionmachines/SDSlite#6]
I am trying to use this lib to read a netcdf-file, but having problem to set it up.
Have tried to use the 32-bit versions of netcdf 4.7.0 and the version from the link on the readme 4.3.3.1.

Howto fix this problem? 

Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'NetCDFInterop!NetCDFInterop.NetCDFDynamic+nc_set_chunk_cache::Invoke' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

**Comment by vassilyl** [comment]
Which OS/platform/framework are you using?

**Comment by Auberginn** [comment]
Same problem here. Using VS2015 on Windows 10. Using SDSLite v1.4.0 from nuget.org

**Comment by vassilyl** [comment]
It turns out the message is from a [Managed Debugging Assistant](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/diagnosing-errors-with-managed-debugging-assistants). The library we use to generate native calls uses calling convention which is different from the one the native netcdf library expects. Actually, PInvoke subsystem is intelligent enough to properly compensate for the difference, and I've never seen this causing an issue. So my suggestion is to ignore the Visual Studio debugger message. You may also turn off the MDA as explained at the linked doc.

**Comment by Auberginn** [comment]
Hi, it seems ok by turning off the PInvokeStackImbalance. Thanks vassilyl
